### DISCUSSION TITLE
Increase font size of snippet description part?

### DISCUSSION THREAD

**Discussion by GG-Delta** [massCodeIO/massCode#369] [Q&A]
Hey there, 
I am currently checking out massCode and I was wandering whether there is a way to increase the text size in the description text of a given snippet? The settings to change font sizes I found are restricted to the Editor part. However, I would need to change the text size of the description text (please see the screenshot). Any hint or advice would be great! Thanks a lot, Gernot

<img width="897" alt="Screenshot 2023-06-05 at 10 31 29" src="https://github.com/massCodeIO/massCode/assets/92456300/2e4d4854-6547-49c8-9950-54aa3cac1ef2">

**Comment by willasm** [comment]
I have to second this. At my age it has become very difficult to read very small print. To get around this I am using dev Tools to edit the default settings. This also adds a border between the snippet name and the description as well as increases the height of the text area for the description. The default of 58px is way to small for any description more than 2 lines long. A height of 146 aligns with the height of the search box plus the first 2 snippets perfectly. This is of course only lasts while the program is still open so has to be entered every time I want to use it. This is not to bad as if I am in a programming session I will have this open in the background for hours. Still it would be nice if these were added as options in the settings so they are permanent.

```css
/* Change Font Size */
.description[data-v-01b5a5e8] {
  fontSize: '17px',
}

/* Change Height and add border */
.description[data-v-01b5a5e8] .ps {
  height: '146px';
  border-top: solid 1px var(--color-border);
  padding-top: 5px;
}
```

and this is the result I get...
![massCode](https://github.com/massCodeIO/massCode/assets/94352899/276dd927-514e-486d-ab00-6c69591d6af1)
